echo >{global.mmu_selector_file} "; AUTOGENERATED FILE DO NOT EDIT"
echo >>{global.mmu_selector_file} "set global.mmu_selector_pos = " ^ global.mmu_selector_pos
echo >>{global.mmu_selector_file} "set global.mmu_extruder_loaded = " ^ global.mmu_extruder_loaded
